import "./globals.scss";
import Header from "@/components/Header";
import type { Metadata } from "next";
import localFont from "next/font/local";

const poppins = localFont({
  src: [
    {
      path: "../../public/fonts/Poppins-Black.ttf",
      weight: "900",
      style: "black",
    },
    {
      path: "../../public/fonts/Poppins-BlackItalic.ttf",
      weight: "900",
      style: "italic",
    },
    {
      path: "../../public/fonts/Poppins-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/Poppins-BoldItalic.ttf",
      weight: "700",
      style: "italic",
    },
    {
      path: "../../public/fonts/Poppins-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/Poppins-MediumItalic.ttf",
      weight: "500",
      style: "italic",
    },
    {
      path: "../../public/fonts/Poppins-Regular.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  display: "swap",
});

// TODO: bom aplicar em cada pagina. Se SEO é importante, vale a pena estudar metadata
// pro caso de alguma pagina ser client-side, é bom fazer um layout pra ela só pra que seja possivel definir esse cara, e até mesmo pra aproveitar pra aplicar aquele design pattern pra requisitar dados nele e passar pro children
// Se os metadados sao definidos no layout, qualquer pagina dentro da pasta a quem o layout pertence, vao usar esses metadados
// Caso for aplicar metadados em uma pagina especifica, precisa ser server-side
// Geralmente onde tem reatividade, precisará ser um componente client-side, entao, da pra pegar esse pedacinho unico q tem interatividade e tentar apartá-lo pra ser uma pecinha reativa com client-side, e tentar tornar o componente q tem ele internamente, um server-side
export const metadata: Metadata = {
  title: "CMS",
  description: "Generated by create next app",
  keywords: ["nextjs", "prismic", "cms"],
  openGraph: {
    title: "CMS",
    // é a imagem que voce quer que apareça como preview pra buscadores e pode ser um screenshot do projeto upado em algum lugar
    images: [
      "http://localhost:3000/_next/image?url=%2Fimages%2Fbanner-exemplo.jpg&w=128&q=75",
    ],
  },
  robots: {
    index: true,
    follow: true,
    nocache: true,
    googleBot: {
      index: true,
      follow: true,
      noimageindex: true,
    },
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={poppins.className}>
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
